server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: solicitud-service
          uri: lb://solicitud-service
          predicates:
            - Path=/solicitud/**
        - id: clock-service
          uri: lb://clock-service
          predicates:
            - Path=/clocks/**
        - id: sueldo-service
          uri: lb://sueldo-service
          predicates:
            - Path=/sueldo/** 
        - id: sueldo-service
          uri: lb://sueldo-service
          predicates:
            - Path=/actuator/**        